#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/16d45adb-d764-41ea-b42a-c9277b180694/ # 
title: auto

/hello:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message": policies
              }